//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PzssCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PzssCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można załadować pliku danych dostępowych lub plik nie ma poprawnego formatu..
        /// </summary>
        internal static string ErrorLoadCred {
            get {
                return ResourceManager.GetString("ErrorLoadCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można odkodować danych dostępowych.
        /// </summary>
        internal static string ErrorUnableToDecode {
            get {
                return ResourceManager.GetString("ErrorUnableToDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany błąd.
        /// </summary>
        internal static string ErrorUnknownError {
            get {
                return ResourceManager.GetString("ErrorUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zalogować do portalu PZSS.
        /// </summary>
        internal static string ErrorWebSignInFailed {
            get {
                return ResourceManager.GetString("ErrorWebSignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można odnaleźć pliku danych dostępowych.
        /// </summary>
        internal static string InfoLoadCredFile {
            get {
                return ResourceManager.GetString("InfoLoadCredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz teraz utworzyć plik danych dostępowych? [Y/n].
        /// </summary>
        internal static string InfoNewCredentialsWelcomeString {
            get {
                return ResourceManager.GetString("InfoNewCredentialsWelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono licencji.
        /// </summary>
        internal static string InfoNoLicensesFound {
            get {
                return ResourceManager.GetString("InfoNoLicensesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź login:.
        /// </summary>
        internal static string InfoPleaseEnterLogin {
            get {
                return ResourceManager.GetString("InfoPleaseEnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź hasło:.
        /// </summary>
        internal static string InfoPleaseEnterPassword {
            get {
                return ResourceManager.GetString("InfoPleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://portal.pzss.org.pl/Player/Licence/List.
        /// </summary>
        internal static string PzssLicenseListPage {
            get {
                return ResourceManager.GetString("PzssLicenseListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://portal.pzss.org.pl.
        /// </summary>
        internal static string PzssLoginPage {
            get {
                return ResourceManager.GetString("PzssLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Player/Player/Profile.
        /// </summary>
        internal static string PzssPortalCorrectSignInAbsUrl {
            get {
                return ResourceManager.GetString("PzssPortalCorrectSignInAbsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string UserResponseNegative {
            get {
                return ResourceManager.GetString("UserResponseNegative", resourceCulture);
            }
        }
    }
}
